// AUTO-GENERATED starter catalog, pulled from the legacy Excel workbook
// (Summit Sensory Gym START - PSF - Single Quote - v73.xlsm) on 2026-07-12.
// Vendor = null means the source spreadsheet didn't specify one -- assign it
// via the product edit page once you know who supplies these SKUs.

export const seedVendorNames = [
  "Amazon/Various",
  "Goldberg",
  "Productive Tool Products",
  "Resilite"
] as const;

export type SeedProduct = {
  sku: string;
  name: string;
  category: string;
  series: "adventure" | "soar" | "flex" | "scape" | "safe";
  vendorName: string | null;
  unitCost: string;
  unitPrice: string;
  weightLbs: string;
};

export const seedProducts: SeedProduct[] = [
  { sku: "A-2245", name: "Vertical Tall <80 w/Gusset", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "242.50", unitPrice: "557.75", weightLbs: "136.50" },
  { sku: "A-2246", name: "Vertical Tall <80 w/Gussets, Rungs & Handles", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "242.50", unitPrice: "557.75", weightLbs: "134.58" },
  { sku: "A-2241", name: "Corner Post <80 1-Way Weld Assembly", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "73.00", unitPrice: "167.90", weightLbs: "0.00" },
  { sku: "A-2242", name: "Corner Post <80 2-Way Weld Assembly", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "76.50", unitPrice: "175.95", weightLbs: "59.73" },
  { sku: "A-2243", name: "Corner Post <80 3-Way Weld Assembly", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "97.00", unitPrice: "223.10", weightLbs: "0.00" },
  { sku: "A-2244", name: "Corner Post <80 4-Way Weld Assembly", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "101.00", unitPrice: "232.30", weightLbs: "0.00" },
  { sku: "A-2022", name: "Corner Post Multi-Level 1-Way Weld Assembly", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "72.50", unitPrice: "166.75", weightLbs: "0.00" },
  { sku: "A-2225", name: "Mid Span 1-Way Saddle Alt Weld Assembly", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "46.00", unitPrice: "105.80", weightLbs: "25.84" },
  { sku: "P-2531", name: "Ladder Leg Footless", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "97.50", unitPrice: "224.25", weightLbs: "61.82" },
  { sku: "A-2253", name: "Single Leg Inner Ladder Sleeve Footless Weld Assembly", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "65.50", unitPrice: "150.65", weightLbs: "8.98" },
  { sku: "A-2248", name: "Double Leg Inner Ladder Sleeve", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "79.00", unitPrice: "181.70", weightLbs: "0.00" },
  { sku: "P-2545", name: "5' Full Bay HSS Member Alt w/ Logo", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "150.00", unitPrice: "345.00", weightLbs: "0.00" },
  { sku: "P-2206", name: "6' Full Bay HSS Member Alt w/ Logo", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "150.00", unitPrice: "345.00", weightLbs: "0.00" },
  { sku: "P-2207", name: "7' Full Bay HSS Member Alt w/ Logo", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "150.00", unitPrice: "345.00", weightLbs: "0.00" },
  { sku: "A-2408", name: "8' Half Bay <80 HSS Member w/Splices & HDWE", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "190.00", unitPrice: "437.00", weightLbs: "98.52" },
  { sku: "A-2409", name: "9' Half Bay <80 HSS Member w/Splices & HDWE", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "200.00", unitPrice: "460.00", weightLbs: "0.00" },
  { sku: "A-2410", name: "10' Half Bay <80 HSS Member w/Splices & HDWE", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "200.00", unitPrice: "460.00", weightLbs: "135.80" },
  { sku: "P-2330", name: "Monkey Bar / Ladder Rungs w/ 4 Threaded Holes", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "20.50", unitPrice: "47.15", weightLbs: "45.41" },
  { sku: "P-2216", name: "6' Full Bay Monkey Bar HSS Member w/ Logo", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "150.00", unitPrice: "345.00", weightLbs: "0.00" },
  { sku: "P-2217", name: "7' Full Bay Monkey Bar HSS Member w/ Logo", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "150.00", unitPrice: "345.00", weightLbs: "0.00" },
  { sku: "A-2418", name: "8' Half Bay Monkey Bar HSS Member w/ Logo", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "190.00", unitPrice: "437.00", weightLbs: "0.00" },
  { sku: "A-2419", name: "9' Half Bay <80 Monkey Bar HSS w/Splices & HDWE", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "200.00", unitPrice: "460.00", weightLbs: "0.00" },
  { sku: "A-2420", name: "10' Half Bay <80 Monkey Bar HSS w/Splices & HDWE", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "200.00", unitPrice: "460.00", weightLbs: "132.44" },
  { sku: "P-2024", name: "Zip Line HSS Tube", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "20.00", unitPrice: "30.00", weightLbs: "11.26" },
  { sku: "A-2530", name: "Zip Line Collar", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "53.00", unitPrice: "79.50", weightLbs: "18.00" },
  { sku: "P-2124", name: "Quick Shift Saddle Bracket\u2122", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "51.00", unitPrice: "117.30", weightLbs: "19.32" },
  { sku: "P-2028", name: "Base Plate Shield", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "25.00", unitPrice: "57.50", weightLbs: "22.48" },
  { sku: "P-2500", name: "Safety First Climbing Shield (48\" x 18\")", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "52.00", unitPrice: "119.60", weightLbs: "0.00" },
  { sku: "P-2501", name: "Safety First Ladder Climbing Shield (90\u00b0 Angle)", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "52.00", unitPrice: "119.60", weightLbs: "22.00" },
  { sku: "P-2502", name: "Safety First Ladder Climbing Shield (50\u00b0 Angle)", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "52.00", unitPrice: "119.60", weightLbs: "23.00" },
  { sku: "P-1032", name: "4.5' Full Bay HSS Member Alt w/Logo", category: "frame_structural", series: "adventure", vendorName: "Goldberg", unitCost: "155.00", unitPrice: "356.50", weightLbs: "0.00" },
  { sku: "P-2018", name: "Trolley Bar", category: "trolley", series: "adventure", vendorName: "Productive Tool Products", unitCost: "14.00", unitPrice: "32.20", weightLbs: "0.00" },
  { sku: "P-2025", name: "Trolley Bar Plate", category: "trolley", series: "adventure", vendorName: "Productive Tool Products", unitCost: "12.00", unitPrice: "27.60", weightLbs: "0.00" },
  { sku: "TR2000-A10", name: "10' Aluminum Enclosed Rail 550lbs. Max Weight", category: "trolley", series: "adventure", vendorName: "Productive Tool Products", unitCost: "215.10", unitPrice: "494.73", weightLbs: "0.00" },
  { sku: "TR2000-A09", name: "9' Aluminum Enclosed Rail 550lbs. Max Weight", category: "trolley", series: "adventure", vendorName: "Productive Tool Products", unitCost: "193.16", unitPrice: "444.27", weightLbs: "0.00" },
  { sku: "TR2000-A08", name: "8' Aluminum Enclosed Rail 550lbs. Max Weight", category: "trolley", series: "adventure", vendorName: "Productive Tool Products", unitCost: "170.72", unitPrice: "392.66", weightLbs: "0.00" },
  { sku: "TR2000-A07", name: "7' Aluminum Enclosed Rail 550lbs. Max Weight", category: "trolley", series: "adventure", vendorName: "Productive Tool Products", unitCost: "151.20", unitPrice: "347.76", weightLbs: "0.00" },
  { sku: "TRH2005", name: "Universal Threaded Rod Hanger", category: "trolley", series: "adventure", vendorName: "Productive Tool Products", unitCost: "99.66", unitPrice: "229.22", weightLbs: "0.00" },
  { sku: "TRN2016", name: "End Cap for Rail", category: "trolley", series: "adventure", vendorName: "Productive Tool Products", unitCost: "46.75", unitPrice: "107.53", weightLbs: "0.00" },
  { sku: "TRT2001", name: "Trolley for Rail", category: "trolley", series: "adventure", vendorName: "Productive Tool Products", unitCost: "93.49", unitPrice: "215.03", weightLbs: "0.00" },
  { sku: "A-2216", name: "Summit Adventure Slide", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "252.00", unitPrice: "1155.00", weightLbs: "0.00" },
  { sku: "B01MUEBGVK", name: "Summit Adventure Slide - 2Piece Plastic Scoop Slide", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "136.00", unitPrice: "1155.00", weightLbs: "0.00" },
  { sku: "B0018L8RJG", name: "Summit Adventure Slide - 2Piece Plastic Scoop Slide", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "136.00", unitPrice: "1028.71", weightLbs: "0.00" },
  { sku: "WS8203", name: "Summit Adventure Slide - Gray Slide Upcharge", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "347.00", unitPrice: "489.27", weightLbs: "0.00" },
  { sku: "150045", name: "Steamroller Ramp", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "977.00", unitPrice: "1377.57", weightLbs: "0.00" },
  { sku: "A-2349", name: "Adventure Steamroller/Scooter Board - Conversion Kit (Required)", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "81.00", unitPrice: "121.50", weightLbs: "3.50" },
  { sku: "B07V3J9S2R", name: "10' x 8' - Climbing Cargo Net Black", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "354.19", unitPrice: "531.28", weightLbs: "0.00" },
  { sku: "B07TSDMPNQ", name: "8' x 6' - Climbing Cargo Net Black", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "227.90", unitPrice: "341.85", weightLbs: "0.00" },
  { sku: "SSG-SA-CFM", name: "Adventure Climbing Wall - Frame Mounted (Includes Climbing Holds)", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "825.00", unitPrice: "1897.50", weightLbs: "0.00" },
  { sku: "SSG-SA-CWM", name: "Adventure Climbing Wall - Wall Mounted-Metal Studs (Includes Climbing Holds)", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "1062.00", unitPrice: "2442.60", weightLbs: "241.00" },
  { sku: "T11412", name: "Adjustable Indoor Climbing Wall", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "1199.95", unitPrice: "2037.96", weightLbs: "0.00" },
  { sku: "SSG-SA-HOLDS", name: "Colored Climbing Holds", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "35.99", unitPrice: "61.12", weightLbs: "0.00" },
  { sku: "SSG-SA-HOLD-SCREWS", name: "Climbing Hold Connection Hardware", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "28.46", unitPrice: "48.34", weightLbs: "0.00" },
  { sku: "SSG-SA-CLIMB-WALL-MOUNT-KIT-ONLY", name: "Adventure Climbing Wall - Conversion Kit", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "185.34", unitPrice: "314.78", weightLbs: "0.00" },
  { sku: "K-5000", name: "Adventure Frame Mount Therapy Ball Rack (Length: 6')", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "192.00", unitPrice: "326.09", weightLbs: "0.00" },
  { sku: "SSCW67", name: "Adventure Complete Column Wrap (67\" x 4.875\" x 3.5\" x 1.375\" )", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "145.00", unitPrice: "221.13", weightLbs: "0.00" },
  { sku: "SSUSP67", name: "Adventure U Shaped Safety Column Wrap (67\" x 3.5\" x 4.875\" x 3.5\" x 1.375\" )", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "155.00", unitPrice: "236.38", weightLbs: "0.00" },
  { sku: "SSUSP72", name: "Adventure U Shaped Column Wrap Ladder Leg (72\" x 2\" x 3.875\" x 2\" x 1.375\" )", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "132.00", unitPrice: "201.30", weightLbs: "0.00" },
  { sku: "SSTBW515", name: "Zip Line Cable Safety Cover", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "20.00", unitPrice: "34.50", weightLbs: "0.00" },
  { sku: "R-SSA-0806CLM", name: "Adventure Floor Mat System (8' x 6' x 3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "773.88", unitPrice: "1083.43", weightLbs: "0.00" },
  { sku: "R-SSA-0909CLM", name: "Adventure Floor Mat System (9' x 9' x 3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1217.59", unitPrice: "1704.63", weightLbs: "0.00" },
  { sku: "R-SSA-0908CLM", name: "Adventure Floor Mat System (9' x 8' x 3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1097.83", unitPrice: "1536.96", weightLbs: "0.00" },
  { sku: "R-SSA-0907CLM", name: "Adventure Floor Mat System (9' x 7' x 3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "978.07", unitPrice: "1369.30", weightLbs: "0.00" },
  { sku: "R-SSA-1010CLM", name: "Adventure Floor Mat System (10' x 10' x 3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1468.90", unitPrice: "2056.46", weightLbs: "0.00" },
  { sku: "R-SSA-1009CLM", name: "Adventure Floor Mat System (10' x 9' x 3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1337.36", unitPrice: "1872.30", weightLbs: "0.00" },
  { sku: "R-SSA-1008CLM", name: "Adventure Floor Mat System (10' x 8' x 3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1205.81", unitPrice: "1688.13", weightLbs: "0.00" },
  { sku: "R-SSA-1007CLM", name: "Adventure Floor Mat System (10' x 7' x 3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1074.27", unitPrice: "1503.98", weightLbs: "0.00" },
  { sku: "R-SSA-1006CLM", name: "Adventure Floor Mat System (10' x 6' x CLM-3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "942.73", unitPrice: "1319.82", weightLbs: "0.00" },
  { sku: "R-SSA-2010CLM", name: "Adventure Floor Mat System (20' x 10' x CLM-3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "2784.33", unitPrice: "3898.06", weightLbs: "0.00" },
  { sku: "R-SSA-2008CLM", name: "Adventure Floor Mat System (20' x 8' x CLM-3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "2285.65", unitPrice: "3199.91", weightLbs: "0.00" },
  { sku: "R-SSA-2007CLM", name: "Adventure Floor Mat System (20' x 7' x CLM-3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "2036.30", unitPrice: "2850.82", weightLbs: "0.00" },
  { sku: "R-SSA-1610CLM", name: "Adventure Floor Mat System (16' x 10' x CLM-3.25\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "2258.16", unitPrice: "3161.42", weightLbs: "0.00" },
  { sku: "R-SSA-88CLM-2", name: "Adventure Floor Mat System (8' x 8' x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "642.81", unitPrice: "899.93", weightLbs: "0.00" },
  { sku: "R-SSA-86CLM-2", name: "Adventure Floor Mat System (8' x 6' x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "502.56", unitPrice: "703.58", weightLbs: "0.00" },
  { sku: "R-SSA-99CLM-2", name: "Adventure Floor Mat System (9' x 9' x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "790.71", unitPrice: "1106.99", weightLbs: "0.00" },
  { sku: "R-SSA-98CLM-2", name: "Adventure Floor Mat System (9' x 8' x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "712.94", unitPrice: "998.12", weightLbs: "0.00" },
  { sku: "R-SSA-97CLM-2", name: "Adventure Floor Mat System (9' x 7' x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "635.16", unitPrice: "889.22", weightLbs: "0.00" },
  { sku: "R-SSA-1010CLM-2", name: "Adventure Floor Mat System (10' x 10' x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "953.91", unitPrice: "1335.47", weightLbs: "0.00" },
  { sku: "R-SSA-1009CLM-2", name: "Adventure Floor Mat System (10' x 9' x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "868.49", unitPrice: "1215.89", weightLbs: "0.00" },
  { sku: "R-SSA-1008CLM-2", name: "Adventure Floor Mat System (10' x 8' x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "783.06", unitPrice: "1096.28", weightLbs: "0.00" },
  { sku: "R-SSA-1007CLM-2", name: "Adventure Floor Mat System (10' x 7' x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "697.64", unitPrice: "976.70", weightLbs: "0.00" },
  { sku: "R-SSA-1006CLM-2", name: "Adventure Floor Mat System (10' x 6' x CLM-2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "612.21", unitPrice: "857.09", weightLbs: "0.00" },
  { sku: "R-SSA-2010CLM-2", name: "Adventure Floor Mat System (20' x 10' x CLM-2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1808.16", unitPrice: "2531.42", weightLbs: "0.00" },
  { sku: "R-SSA-2008CLM-2", name: "Adventure Floor Mat System (20' x 8' x CLM-2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1484.31", unitPrice: "2078.03", weightLbs: "0.00" },
  { sku: "R-SSA-2007CLM-2", name: "Adventure Floor Mat System (20' x 7' x CLM-2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1466.46", unitPrice: "2053.04", weightLbs: "0.00" },
  { sku: "R-SSA-1610CLM-2", name: "Adventure Floor Mat System (16' x 10' x CLM-2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1322.39", unitPrice: "1851.35", weightLbs: "0.00" },
  { sku: "CUST-LOGO", name: "Custom Branding Setup (Logo Application on Mats & Padding)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1250.00", unitPrice: "1562.50", weightLbs: "0.00" },
  { sku: "EXTENSION", name: "Adventure Floor Mat System Extensions - 168 Sq Ft of Padding Around Frame", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "2315.04", unitPrice: "3472.56", weightLbs: "0.00" },
  { sku: "CUSTOM", name: "Custom Mat Design & Size", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "0.00", unitPrice: "0.00", weightLbs: "0.00" },
  { sku: "DLR-LM48302", name: "Adventure Floor Safety Mat (4' x 8' x 8\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "638.00", unitPrice: "957.00", weightLbs: "0.00" },
  { sku: "WCC2101", name: "Adventure Wall Padding (24\" x 60\" x 2\") Wainscot Panel w/ Lip", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "98.00", unitPrice: "147.00", weightLbs: "0.00" },
  { sku: "WCC2102", name: "Adventure Wall Padding (24\" x 72\" x 2\") Wainscot Panel w/ Lip", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "103.00", unitPrice: "154.50", weightLbs: "0.00" },
  { sku: "COLL4812", name: "Adventure Wall Corner Padding (72\" x 6\" x 6\" x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "128.00", unitPrice: "192.00", weightLbs: "0.00" },
  { sku: "WCOC01", name: "Adventure Wall Padding - Rubber Outlet Insert", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "55.00", unitPrice: "82.50", weightLbs: "0.00" },
  { sku: "SSRSEM462-L", name: "Adventure Flip-Up Safety Mat (4' x 6' x 2\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "290.00", unitPrice: "435.00", weightLbs: "0.00" },
  { sku: "SRFM200X", name: "Adventure Rear Climbing Wall Safety Mat (48\" x 83\" x 2' Single-Fold w/ 4 Grommets)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "339.00", unitPrice: "508.50", weightLbs: "0.00" },
  { sku: "CP4x8BL-4IN", name: "Medium Crash Pads 4\" Thick (4' Wide x 8' Long - Unfolded)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "419.99", unitPrice: "629.99", weightLbs: "0.00" },
  { sku: "CP4x8BL-8IN", name: "Large Crash Pads 8\" Thick (4' Wide x 8' Long - Unfolded)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "445.00", unitPrice: "600.75", weightLbs: "0.00" },
  { sku: "CP4x8BL-12IN", name: "Large Crash Pads 12\" Thick (4' Wide x 8' Long - Unfolded)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "879.99", unitPrice: "1187.99", weightLbs: "0.00" },
  { sku: "RSS2432", name: "Adventure Soft-Steps (2 Steps)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "184.00", unitPrice: "276.00", weightLbs: "0.00" },
  { sku: "RSS2433", name: "Adventure Soft-Steps (3 Steps)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "211.00", unitPrice: "316.50", weightLbs: "0.00" },
  { sku: "RPAL6868", name: "Palisades Therapy Mat System", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "2553.00", unitPrice: "3063.60", weightLbs: "0.00" },
  { sku: "RMP9628", name: "Adventure 96\" Extra Large Ball Pit (Does Not Include Plastic Balls)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "2345.00", unitPrice: "3165.75", weightLbs: "130.00" },
  { sku: "SS72BP", name: "Adventure 72\" Large Ball Pit (Does Not Include Plastic Balls)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1552.00", unitPrice: "2095.20", weightLbs: "0.00" },
  { sku: "SS48BP", name: "Adventure 48\" Small Ball Pit (Does Not Include Plastic Balls)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1007.00", unitPrice: "1359.45", weightLbs: "0.00" },
  { sku: "SS7248BP", name: "Adventure 72\" x 48\" Ball Pit (Does Not Include Plastic Balls)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1315.00", unitPrice: "1775.25", weightLbs: "0.00" },
  { sku: "PSB-BPSM", name: "Adventure 58\" x 58\" Ball Pit OD (Does Not Include Plastic Balls)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1216.80", unitPrice: "1642.68", weightLbs: "0.00" },
  { sku: "PSB-BPMD", name: "Adventure 82\" x 82\" Ball Pit Outside Dimensions (Does Not Include Plastic Balls)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1439.20", unitPrice: "1942.92", weightLbs: "0.00" },
  { sku: "PSB-BPLG", name: "Adventure 106\" x 106\" Ball Pit Outside Dimensions (Does Not Include Plastic Balls)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1640.00", unitPrice: "2214.00", weightLbs: "0.00" },
  { sku: "RCLSD5630", name: "Adventure Climb & Slide (90 Degree)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1317.00", unitPrice: "1843.80", weightLbs: "0.00" },
  { sku: "RLW758", name: "72\" x 178\" x 1.625\" Light Weight Mat w/Resi-lock", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "675.04", unitPrice: "1266.75", weightLbs: "0.00" },
  { sku: "RLW758-1", name: "49\" x 124\" x 1.625\" Light Weight Mat w/Resi-lock", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "412.46", unitPrice: "774.00", weightLbs: "0.00" },
  { sku: "24722", name: "24\" x 72\" x 2\" Therapy Mat", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "125.00", unitPrice: "168.75", weightLbs: "0.00" },
  { sku: "48722", name: "48\" x 72\" x 2\" Therapy Mat", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "202.00", unitPrice: "272.70", weightLbs: "0.00" },
  { sku: "B09T76V33V", name: "Cargo Net Attachment Double Slackline", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "39.99", unitPrice: "59.99", weightLbs: "0.00" },
  { sku: "XL-PLAT", name: "Platform Swing XL (48\" x 60\") - Holds Up to 500lbs", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "400.00", unitPrice: "1176.29", weightLbs: "0.00" },
  { sku: "B0BGDQF46S", name: "Ninja Warrior Obstacle Course for Kids up to 880 lbs & 13 Obstacles", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "206.45", unitPrice: "309.68", weightLbs: "0.00" },
  { sku: "B08SMN18WG", name: "Safety Net - 6.5' X 9.8'", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "89.99", unitPrice: "134.99", weightLbs: "0.00" },
  { sku: "B0193YG8GI", name: "18\" Trapeze Swing Bar", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "21.69", unitPrice: "32.54", weightLbs: "0.00" },
  { sku: "B07MC3144W", name: "2PCS Swings Seats Heavy Duty - Supports 250 lbs", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "41.31", unitPrice: "61.97", weightLbs: "0.00" },
  { sku: "B07PQHSZPR", name: "Climbing Rope with Platforms and Disc Swing Seat Set", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "30.37", unitPrice: "45.56", weightLbs: "0.00" },
  { sku: "B0894XNGJP", name: "Calming Cocoon Therapy Swing - Supports 300 lbs", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "47.49", unitPrice: "71.24", weightLbs: "0.00" },
  { sku: "B07WGZP8XT", name: "Ninja Warrior Obstacle Course Accessories Ninja Kids Outdoor Play - 7pc Ninja Rings, 2pc Swing Trapeze Wheels & 2pc Ninja Monkey Bars", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "59.83", unitPrice: "89.75", weightLbs: "0.00" },
  { sku: "B0937DRYYF", name: "50 Pack Heavy Duty Snap Hooks M8 5/16\" Carabiner Clips", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "36.00", unitPrice: "82.80", weightLbs: "0.00" },
  { sku: "B0CDVDZSB1", name: "Auto Locking Carabiner Clips - 28KN (6172lbs) Heavy Duty Carabiner (4 Pack)", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "22.99", unitPrice: "52.88", weightLbs: "0.00" },
  { sku: "RDC6015-B", name: "60\" Multi-Pocket Webbing Slings (Loop strength 1,200 lbf. (5.3 kN)) (Black)", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "23.99", unitPrice: "55.18", weightLbs: "0.00" },
  { sku: "B08DTP539F", name: "Trobing Swing Swivel", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "23.98", unitPrice: "55.15", weightLbs: "0.00" },
  { sku: "B07Z79ZCZX", name: "Rotary Soft Nylon Sensory Swing with Swivel - Holds Up to 200lbs", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "125.00", unitPrice: "287.50", weightLbs: "0.00" },
  { sku: "B07MB985GW", name: "V-Ring 2\" Diameter Steel V-Ring Bolt (10 Pack)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "19.79", unitPrice: "45.52", weightLbs: "0.00" },
  { sku: "B01C3I4SL8", name: "Skateboard Swing Standing", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "76.49", unitPrice: "175.93", weightLbs: "0.00" },
  { sku: "ZIPLINE-WIRE", name: "Zip Line Wiring Kit (Pulley & Other Accessories Not Included)", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "115.00", unitPrice: "172.50", weightLbs: "0.00" },
  { sku: "ZIPLINE-TROLLEY", name: "Zip Line Pulley Tandem Speed Dual Trolley with 25kN Carabiner", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "45.00", unitPrice: "67.50", weightLbs: "0.00" },
  { sku: "6820H-LP-ZP", name: "Zip Line Fixed Eye Bolt", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "8.95", unitPrice: "20.59", weightLbs: "0.00" },
  { sku: "B01MRLJ93K", name: "Zip Line Cable Sleeve (Designed to Reduce Noise)", category: "accessory", series: "adventure", vendorName: "Amazon/Various", unitCost: "15.83", unitPrice: "36.41", weightLbs: "0.00" },
  { sku: "120040", name: "Platform Swing w/ Carpet Cover", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "275.00", unitPrice: "385.00", weightLbs: "0.00" },
  { sku: "120050", name: "Advantage Line Bolster Swing", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "375.00", unitPrice: "525.00", weightLbs: "0.00" },
  { sku: "120077", name: "Rainbow Acrobat Swing", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "529.00", unitPrice: "740.60", weightLbs: "0.00" },
  { sku: "1909", name: "Flexion Disc Swing", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "419.00", unitPrice: "586.60", weightLbs: "0.00" },
  { sku: "815DBLESTK", name: "Double Layer Therapy Net", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "509.21", unitPrice: "712.89", weightLbs: "0.00" },
  { sku: "120145", name: "Large 3-in-1 Barrel Swing", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "955.00", unitPrice: "1337.00", weightLbs: "0.00" },
  { sku: "382-408_x000D_", name: "Wheelchair Swing Platform - Adult", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "1407.00", unitPrice: "2110.50", weightLbs: "0.00" },
  { sku: "B0C4YB8D64", name: "Wheelchair Swing Swing Hangers with Bearing", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "17.09", unitPrice: "39.31", weightLbs: "0.00" },
  { sku: "382-411", name: "Jenn Swing ADA Seat", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "482.25", unitPrice: "723.38", weightLbs: "0.00" },
  { sku: "T00207", name: "Adult - TFH High Backed Seat Swing", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "449.00", unitPrice: "673.50", weightLbs: "0.00" },
  { sku: "8SQMC", name: "Summit Sensory Squeeze Machine", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "543.20", unitPrice: "733.32", weightLbs: "0.00" },
  { sku: "1001", name: "Standard Deluxe Bolster Swing", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "699.00", unitPrice: "1085.20", weightLbs: "0.00" },
  { sku: "4602", name: "Variable Axis Swing & Footrest", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "997.00", unitPrice: "1547.84", weightLbs: "0.00" },
  { sku: "B09XV985JJ", name: "56\" Dual Trampoline 220LBS Capacity w Adjustable Safety Handrail", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "105.00", unitPrice: "163.01", weightLbs: "0.00" },
  { sku: "DL24LG0.1-25M", name: "Thick Multipurpose Interlocking Mats (24' x 24\" x 1\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "8.13", unitPrice: "11.99", weightLbs: "0.00" },
  { sku: "EST-SQFT", name: "Protective Flooring Mat Coverage - Estimated 0 Square Footage", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "0.00", unitPrice: "0.00", weightLbs: "0.00" },
  { sku: "3RD-FREIGHT", name: "Passthrough Freight Charge", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "0.00", unitPrice: "0.00", weightLbs: "0.00" },
  { sku: "FLEXI-ROLL", name: "Carpet Floor Padding (1-3/8\" Thickness) - Cut to Fit Space", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "3.80", unitPrice: "5.90", weightLbs: "0.00" },
  { sku: "FLEXI-CONNECT", name: "Carpet Tapeless Floor Padding (1-3/8\" Thickness) - Cut to Fit Space", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "4.59", unitPrice: "6.60", weightLbs: "0.00" },
  { sku: "GRPMAT158", name: "Interlocking Floor Tiles (40\" x 40\" x 1.5\")", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "29.50", unitPrice: "42.00", weightLbs: "0.00" },
  { sku: "BR158", name: "Border Ramp (40\" x 40\" x 1.5\") - (2 Pack)", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "11.98", unitPrice: "18.60", weightLbs: "0.00" },
  { sku: "B004NTO8T8", name: "Skil-Care Crash Pad", category: "mat", series: "adventure", vendorName: "Resilite", unitCost: "191.00", unitPrice: "267.40", weightLbs: "0.00" },
  { sku: "6820H-LAD", name: "Playground Handles, Gate Handles 1 handle (B08K2V5G6T)", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "15.00", unitPrice: "34.50", weightLbs: "0.00" },
  { sku: "6820H-LAK", name: "1/2\" x 4\" Strong-Tie THD50400H Titen HD Screw Anchor, Zinc", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "2.75", unitPrice: "6.33", weightLbs: "0.00" },
  { sku: "6820H-LDD", name: "Swing & Swivel Eye Bolt (for Quick Shift Saddle Bracket\u2122)", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "81.06", unitPrice: "158.73", weightLbs: "0.00" },
  { sku: "6820H-LAC-G", name: "Eye Bolt - Fixed (for Quick Shift Saddle Bracket\u2122)", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "6.00", unitPrice: "13.80", weightLbs: "0.00" },
  { sku: "6820H-LP", name: "Eye Bolt - Fixed", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "8.95", unitPrice: "20.59", weightLbs: "0.00" },
  { sku: "B0C4Y8XSNB", name: "Eye Bolt - Swing Hangers w/ Bearing", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "5.84", unitPrice: "13.43", weightLbs: "0.00" },
  { sku: "6820H-LY", name: "Eye Bolt; 1/4-20 X 2 Length", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "6.50", unitPrice: "14.95", weightLbs: "0.00" },
  { sku: "6820H-LAI", name: "Quick Shift Bracket Bent Pin w / Lanyard", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "9.60", unitPrice: "22.07", weightLbs: "0.00" },
  { sku: "6820H-LC", name: "Hex Nylon Insert Lock Nut, Zinc Plated Grade 5 Steel, 1/2-13", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.34", unitPrice: "0.78", weightLbs: "0.00" },
  { sku: "6820H-LX", name: "Flat Shoulder Rod End Bolt 5/16-18 X 1 Shank Thread", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "15.50", unitPrice: "35.65", weightLbs: "0.00" },
  { sku: "6820H-LF", name: "Hex Nylon Insert Lock Nut, Zinc Plated Grade 5 Steel, 3/8-16", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.25", unitPrice: "0.58", weightLbs: "0.00" },
  { sku: "6820H-LB", name: "Washer 1/2 Flat Zinc Plated Grade 5 Steel", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.18", unitPrice: "0.41", weightLbs: "0.00" },
  { sku: "6820H-LA", name: "Hex Bolt, Zinc Plated Grade 5 Steel, 1/2-13 X 4-1/2\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "1.00", unitPrice: "2.30", weightLbs: "0.00" },
  { sku: "6820H-LAG", name: "Hex Bolt, Zinc Plated Grade 5 Steel, 1/2-13 X 4\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.95", unitPrice: "2.19", weightLbs: "0.00" },
  { sku: "6820H-LH", name: "Tap Bolt, Zinc Plated Grade 5 Steel, 3/8-16 X 2-1/4\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.55", unitPrice: "1.27", weightLbs: "0.00" },
  { sku: "6820H-LG", name: "Tap Bolt, Zinc Plated Grade 5 Steel, 3/8-16 X 1-3/4\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.40", unitPrice: "0.92", weightLbs: "0.00" },
  { sku: "6820H-LI", name: "Hex Bolt, Zinc Plated Grade 5 Steel, 1/4-20 X 2-3/4\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.26", unitPrice: "0.60", weightLbs: "0.00" },
  { sku: "6820H-LJ", name: "Hex Bolt, Zinc Plated Grade 5 Steel, 1/4-20 X 4\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.50", unitPrice: "1.15", weightLbs: "0.00" },
  { sku: "6820H-LK", name: "Uss Flat Washer, Zinc Plated Grade 5 Steel, 1/4", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.09", unitPrice: "0.21", weightLbs: "0.00" },
  { sku: "6820H-LL", name: "Hex Nylon Insert Lock Nut, Zinc Plated Grade 5 Steel, 1/4-20", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.14", unitPrice: "0.32", weightLbs: "0.00" },
  { sku: "6820H-LT", name: "Coupling Nut, Zinc Plated Steel, 5/16-18 X 1-3/4", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "1.25", unitPrice: "2.88", weightLbs: "0.00" },
  { sku: "6820H-LAB", name: "Hex Nut, Zinc Plated Grade 5 Steel, 5/16-18", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.11", unitPrice: "0.25", weightLbs: "0.00" },
  { sku: "6820H-LAA", name: "Lock Washer, Zinc Plated Steel, 5/16", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.07", unitPrice: "0.16", weightLbs: "0.00" },
  { sku: "6820H-LU", name: "Uss Flat Washer, Zinc Plated Grade 5 Steel, 5/16", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.09", unitPrice: "0.21", weightLbs: "0.00" },
  { sku: "6820H-LV", name: "Hex Bolt, Zinc Plated Grade 5 Steel, 5/16\"-18 X 1\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.30", unitPrice: "0.69", weightLbs: "0.00" },
  { sku: "6820H-LW", name: "Hex Nylon Insert Lock Nut, Zinc Plated Grade 5 Steel, 5/16-18", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.17", unitPrice: "0.39", weightLbs: "0.00" },
  { sku: "6820H-LQ", name: "Tap Bolt, Zinc Plated Grade 5 Steel, 1/2-13 X 6\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "1.16", unitPrice: "2.67", weightLbs: "0.00" },
  { sku: "6820H-LO", name: "Hex Bolt, Zinc Plated Grade 5 Steel, 1/2-13 X 7\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "1.47", unitPrice: "3.38", weightLbs: "0.00" },
  { sku: "6820H-LR", name: "Hex Nut, Zinc Plated Grade 5 Steel, 1/2-13", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.23", unitPrice: "0.53", weightLbs: "0.00" },
  { sku: "6820H-LM", name: "Uss Flat Washer, Zinc Plated Grade 5 Steel, 3/8", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.10", unitPrice: "0.23", weightLbs: "0.00" },
  { sku: "6820H-LN", name: "Hex Bolt, Zinc Plated Grade 5 Steel, 1/2-13 X 3-1/2\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "1.06", unitPrice: "2.44", weightLbs: "0.00" },
  { sku: "6820H-LS", name: "Rubber Bumpers, 3/4 Od X 1/16 High Black 25 Pack", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "11.00", unitPrice: "25.30", weightLbs: "0.00" },
  { sku: "6820H-LAE", name: "TAP BOLT, ZINC PLATED GRADE 5 STEEL, 3/8-16 X 4\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "1.18", unitPrice: "2.71", weightLbs: "0.00" },
  { sku: "6820H-LAF", name: "V-RING BOLT ON ANCHOR", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "3.42", unitPrice: "7.87", weightLbs: "0.00" },
  { sku: "6820H-LAH", name: "BUTTON HEAD HEX DRIVE SCREW, 3/8\"-16 X 1-1/2\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.84", unitPrice: "1.93", weightLbs: "0.00" },
  { sku: "6820H-LAJ", name: "HEX BOLT, ZINC PLATED GRADE 5 STEEL, 1/2-13 X 5\"", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "1.74", unitPrice: "4.00", weightLbs: "0.00" },
  { sku: "SSG-SA-SWIVEL-EYE", name: "Swing & Swivel Eye Bolt (Stand Alone)", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "100.06", unitPrice: "196.12", weightLbs: "0.00" },
  { sku: "H-1000", name: "Sensory Gym Hardware", category: "hardware", series: "adventure", vendorName: "Goldberg", unitCost: "0.00", unitPrice: "0.00", weightLbs: "0.00" },
  { sku: "K-4000", name: "Summit Soar S1 - Mobile Free-Standing Swing Frame w/ Single Cross Beam", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "1950.00", unitPrice: "3900.00", weightLbs: "460.00" },
  { sku: "K-4002", name: "Summit Soar - Swing Mount Extensions", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "292.00", unitPrice: "511.00", weightLbs: "0.00" },
  { sku: "SOAR-S2", name: "Summit Soar S2 - Mobile Free-Standing Swing Frame w/ Two Cross Beams", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "2242.00", unitPrice: "4411.00", weightLbs: "0.00" },
  { sku: "SOAR-S3", name: "Summit Soar S3 - Mobile Free-Standing Swing Frame w/ Three Cross Beams", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "2534.00", unitPrice: "4922.00", weightLbs: "0.00" },
  { sku: "SOAR-S1-XL", name: "Summit Soar S1-XL - Mobile Free-Standing Swing Frame w/ Single Cross Beam (Width: 12')", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "1950.00", unitPrice: "4329.00", weightLbs: "0.00" },
  { sku: "SOAR-S2-XL", name: "Summit Soar S2-XL - Mobile Free-Standing Swing Frame w/ Two Cross Beams (Width: 12')", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "2578.30", unitPrice: "4840.00", weightLbs: "0.00" },
  { sku: "SOAR-S3-XL", name: "Summit Soar S3-XL - Mobile Free-Standing Swing Frame w/ Three Cross Beams (Width: 12')", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "2914.10", unitPrice: "5351.00", weightLbs: "0.00" },
  { sku: "382-408", name: "Wheelchair Swing Platform - Adult", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "1407.00", unitPrice: "2110.50", weightLbs: "0.00" },
  { sku: "BSP-041-BLKALUHNGW-SO2", name: "2 Hole Heavy Duty Aluminum Swing Hangers", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "43.24", unitPrice: "64.86", weightLbs: "0.00" },
  { sku: "CLM325", name: "Soar-XL Floor Mat System (138\" x 80\" x 3.25\") - Single Fold", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "960.00", unitPrice: "1440.00", weightLbs: "0.00" },
  { sku: "SSM80100", name: "Soar Floor Mat System (100\" x 80\" x 3.25\") - Single Fold", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "695.00", unitPrice: "1042.50", weightLbs: "0.00" },
  { sku: "COLU2812", name: "Soar Base Beam U Column Wrap (30\" x 4.5\" x 3.5\" x 3.5\" x 1.375\")", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "105.00", unitPrice: "178.50", weightLbs: "0.00" },
  { sku: "SFGPC", name: "Gusset Plate Padding", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "130.00", unitPrice: "175.50", weightLbs: "0.00" },
  { sku: "COLW2812", name: "Soar Column Wrap (60\" x 4.5\" x 4.5\" x 1.375\")", category: "frame_and_hardware", series: "soar", vendorName: null, unitCost: "125.00", unitPrice: "221.13", weightLbs: "0.00" },
  { sku: "A-2200", name: "Summit Flex: Universial Excerise Unit (Spider Cage) w/ Hardware", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "2820.00", unitPrice: "5414.40", weightLbs: "400.00" },
  { sku: "UEU-ISTRS", name: "Integrated Suspension Tracking Rail System", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "737.00", unitPrice: "1415.04", weightLbs: "35.00" },
  { sku: "UEU-ISTRS-UNIKIT", name: "Integrated Suspension Tracking Rail System (Universal Conversion Kit)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "792.00", unitPrice: "0.00", weightLbs: "0.00" },
  { sku: "P-2513", name: "Summit Flex: Trolley Rail Rear Bracket", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "20.00", unitPrice: "0.00", weightLbs: "5.00" },
  { sku: "L54", name: "Petzl - Lift Spreader for Harness", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "149.95", unitPrice: "359.88", weightLbs: "0.00" },
  { sku: "FLEX69482", name: "Vertical UEU Rear Frame Padding - 69\" x 48\" x 2\" V1 Folding Mat - 2 Sections", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "284.00", unitPrice: "545.28", weightLbs: "0.00" },
  { sku: "FLEX72482", name: "Vertical UEU Side Frame Padding - 72\" x 48\" x 2\" V1 Folding Mat - 2 Sections", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "284.00", unitPrice: "545.28", weightLbs: "0.00" },
  { sku: "FLEX-VERT-BUNDLE", name: "Vertical UEU Frame Padding Bundle (3 - Vertical UEU Frame Pads)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "852.00", unitPrice: "1405.80", weightLbs: "0.00" },
  { sku: "FLEX69722", name: "Floor Padding - 69\" x 72\" x 2\" V1 Folding Mat - 2 Sections", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "284.00", unitPrice: "574.09", weightLbs: "26.00" },
  { sku: "FLEX-PAD-BUNDLE", name: "Safety Padding Bundle (Includes Vertical Padding & Floor Pad)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "1136.00", unitPrice: "1936.88", weightLbs: "0.00" },
  { sku: "FLEX-BELT-BUNDLE", name: "Flex Leather Belt Bundle (7 Belts - All Sizes) / (1) XX Small Leather Belt / (1) X Small Leather Belt / (1) Small Leather Belt / (1) Medium Leather Belt / (1) Large Leather Belt / (1) X Large Leather Belt / (1) XX Large Leather Belt", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "980.00", unitPrice: "1470.00", weightLbs: "0.00" },
  { sku: "FLEX-BELT-TBD", name: "Leather Belt (Size - TBD)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "140.00", unitPrice: "226.88", weightLbs: "0.00" },
  { sku: "FLEX-BELT-XXS", name: "Leather Belt (Size - XX Small)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "150.00", unitPrice: "226.88", weightLbs: "0.00" },
  { sku: "FLEX-BELT-XS", name: "Leather Belt (Size - X Small)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "150.00", unitPrice: "226.88", weightLbs: "0.00" },
  { sku: "FLEX-BELT-S", name: "Leather Belt (Size - Small)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "150.00", unitPrice: "226.88", weightLbs: "0.00" },
  { sku: "FLEX-BELT-M", name: "Leather Belt (Size - Medium)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "150.00", unitPrice: "226.88", weightLbs: "0.00" },
  { sku: "FLEX-BELT-L", name: "Leather Belt (Size - Large)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "150.00", unitPrice: "226.88", weightLbs: "0.00" },
  { sku: "FLEX-BELT-XL", name: "Leather Belt (Size - X Large)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "150.00", unitPrice: "226.88", weightLbs: "0.00" },
  { sku: "FLEX-BELT-XXL", name: "Leather Belt (Size - XX Large)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "150.00", unitPrice: "226.88", weightLbs: "0.00" },
  { sku: "UEU-HARKIT", name: "Suspension Harness Kit", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "63.26", unitPrice: "204.44", weightLbs: "15.00" },
  { sku: "P-2526", name: "Suspension Spreader Bar", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "10.50", unitPrice: "13.65", weightLbs: "0.00" },
  { sku: "B0983M934C", name: "Nylon Daisy Chain Straps (2 Piece)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "16.19", unitPrice: "21.05", weightLbs: "0.00" },
  { sku: "B01MSIUGTM", name: "30KN CE Certified Micro Rotator Swivel", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "22.77", unitPrice: "29.60", weightLbs: "0.00" },
  { sku: "B0C9Y4Q8WG", name: "Heavy Duty Carabiner (2 Pack)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "13.80", unitPrice: "17.94", weightLbs: "0.00" },
  { sku: "FLEX-RACK", name: "Equipment Rack (Frame Mounted)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "65.00", unitPrice: "107.25", weightLbs: "0.00" },
  { sku: "UEU-THERABUNGEE-23", name: "TheraBungee - 10 Piece Bungee Set", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "180.04", unitPrice: "297.07", weightLbs: "25.00" },
  { sku: "BABY-KIT", name: "Baby Harness Kit", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "399.00", unitPrice: "658.35", weightLbs: "0.00" },
  { sku: "OUISTITI", name: "Petzel - Full Body Youth Harness (Supports Up to 65 lbs)", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "99.00", unitPrice: "163.35", weightLbs: "2.00" },
  { sku: "BASIC", name: "Basic Equipment Set - 69 Elements", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "593.60", unitPrice: "1249.99", weightLbs: "0.00" },
  { sku: "STANDARD", name: "Standard Equipment Set - 82 Elements", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "650.13", unitPrice: "1649.99", weightLbs: "65.00" },
  { sku: "FULL", name: "Full Equipment Set - 132 Elements", category: "parts_and_hardware", series: "flex", vendorName: null, unitCost: "1030.75", unitPrice: "2369.99", weightLbs: "0.00" },
  { sku: "WCC2103", name: "1' 7/8\" x 6' x 2\" Wood-backed Wainscot Panels w 1\" Nailing Lip Top & Bottom", category: "wall_panel", series: "safe", vendorName: null, unitCost: "111.00", unitPrice: "144.30", weightLbs: "0.00" },
  { sku: "WCC2104", name: "2' 3/4\" X 6' X 2\" Wood-backed Wainscot Panels w 1\" Nailing Lip Top & Bottom", category: "wall_panel", series: "safe", vendorName: null, unitCost: "111.00", unitPrice: "144.30", weightLbs: "0.00" },
  { sku: "9WMFO5", name: "Fiber Optic Waterfall Wall Mount", category: "sensory_equipment", series: "scape", vendorName: null, unitCost: "1260.00", unitPrice: "1575.00", weightLbs: "0.00" },
  { sku: "9WMFO5-1", name: "Includes: / 1. Fiber Optic Tails (200) / 2. Sparkle LED Light Source / 3. Clear Acrylic Bracket", category: "sensory_equipment", series: "scape", vendorName: null, unitCost: "0.00", unitPrice: "0.00", weightLbs: "0.00" },
  { sku: "9WMFO5-2", name: "MSE Genie App Controller (iPad or iPhone)", category: "sensory_equipment", series: "scape", vendorName: null, unitCost: "0.00", unitPrice: "0.00", weightLbs: "0.00" },
  { sku: "SP9012", name: "SensaSoft\u2122 Support Vibrochair - Dark Blue - Two chairs, One Speaker Seat", category: "sensory_equipment", series: "scape", vendorName: null, unitCost: "4395.49", unitPrice: "5494.36", weightLbs: "0.00" },
  { sku: "5805-PB", name: "Kid Bean Bag Chair, Pacific Blue", category: "sensory_equipment", series: "scape", vendorName: null, unitCost: "310.00", unitPrice: "387.50", weightLbs: "0.00" },
  { sku: "303805", name: "Sensory Activity Wall", category: "sensory_equipment", series: "scape", vendorName: null, unitCost: "2540.00", unitPrice: "3175.00", weightLbs: "0.00" },
  { sku: "INTERIOR", name: "Sensory & Room Conception Development, Space Planning & Product Sourcing", category: "sensory_equipment", series: "scape", vendorName: null, unitCost: "650.00", unitPrice: "812.50", weightLbs: "0.00" },
];
